<?php

namespace App\Enums;

enum Nationality: string
{
    case Afghan = 'Afghan';
    case Albanian = 'Albanian';
    case Algerian = 'Algerian';
    case American = 'American';
    case Andorran = 'Andorran';
    case Angolan = 'Angolan';
    case Antiguans = 'Antiguans';
    case Argentinean = 'Argentinean';
    case Armenian = 'Armenian';
    case Australian = 'Australian';
    case Austrian = 'Austrian';
    case Azerbaijani = 'Azerbaijani';
    case Bahamian = 'Bahamian';
    case Bahraini = 'Bahraini';
    case Bangladeshi = 'Bangladeshi';
    case Barbadian = 'Barbadian';
    case Belarusian = 'Belarusian';
    case Belgian = 'Belgian';
    case Belizean = 'Belizean';
    case Beninese = 'Beninese';
    case Bhutanese = 'Bhutanese';
    case Bolivian = 'Bolivian';
    case Bosnian = 'Bosnian';
    case Brazilian = 'Brazilian';
    case British = 'British';
    case Bruneian = 'Bruneian';
    case Bulgarian = 'Bulgarian';
    case Burkinabe = 'Burkinabe';
    case Burmese = 'Burmese';
    case Burundian = 'Burundian';
    case Cambodian = 'Cambodian';
    case Cameroonian = 'Cameroonian';
    case Canadian = 'Canadian';
    case CapeVerdean = 'Cape Verdean';
    case CentralAfrican = 'Central African';
    case Chadian = 'Chadian';
    case Chilean = 'Chilean';
    case Chinese = 'Chinese';
    case Colombian = 'Colombian';
    case Comoran = 'Comoran';
    case Congolese = 'Congolese';
    case CostaRican = 'Costa Rican';
    case Croatian = 'Croatian';
    case Cuban = 'Cuban';
    case Cypriot = 'Cypriot';
    case Czech = 'Czech';
    case Danish = 'Danish';
    case Djiboutian = 'Djiboutian';
    case Dominican = 'Dominican';
    case Dutch = 'Dutch';
    case EastTimorese = 'East Timorese';
    case Ecuadorean = 'Ecuadorean';
    case Egyptian = 'Egyptian';
    case Emirian = 'Emirian';
    case EquatorialGuinean = 'Equatorial Guinean';
    case Eritrean = 'Eritrean';
    case Estonian = 'Estonian';
    case Ethiopian = 'Ethiopian';
    case Fijian = 'Fijian';
    case Filipino = 'Filipino';
    case Finnish = 'Finnish';
    case French = 'French';
    case Gabonese = 'Gabonese';
    case Gambian = 'Gambian';
    case Georgian = 'Georgian';
    case German = 'German';
    case Ghanaian = 'Ghanaian';
    case Greek = 'Greek';
    case Grenadian = 'Grenadian';
    case Guatemalan = 'Guatemalan';
    case GuineaBissauan = 'Guinea-Bissauan';
    case Guinean = 'Guinean';
    case Guyanese = 'Guyanese';
    case Haitian = 'Haitian';
    case Herzegovinian = 'Herzegovinian';
    case Honduran = 'Honduran';
    case Hungarian = 'Hungarian';
    case Icelander = 'Icelander';
    case Indian = 'Indian';
    case Indonesian = 'Indonesian';
    case Iranian = 'Iranian';
    case Iraqi = 'Iraqi';
    case Irish = 'Irish';
    case Israeli = 'Israeli';
    case Italian = 'Italian';
    case Ivorian = 'Ivorian';
    case Jamaican = 'Jamaican';
    case Japanese = 'Japanese';
    case Jordanian = 'Jordanian';
    case Kazakhstani = 'Kazakhstani';
    case Kenyan = 'Kenyan';
    case Kittian = 'Kittian';
    case Kuwaiti = 'Kuwaiti';
    case Kyrgyz = 'Kyrgyz';
    case Laotian = 'Laotian';
    case Latvian = 'Latvian';
    case Lebanese = 'Lebanese';
    case Liberian = 'Liberian';
    case Libyan = 'Libyan';
    case Liechtensteiner = 'Liechtensteiner';
    case Lithuanian = 'Lithuanian';
    case Luxembourger = 'Luxembourger';
    case Macedonian = 'Macedonian';
    case Malagasy = 'Malagasy';
    case Malawian = 'Malawian';
    case Malaysian = 'Malaysian';
    case Maldivian = 'Maldivian';
    case Malian = 'Malian';
    case Maltese = 'Maltese';
    case Marshallese = 'Marshallese';
    case Mauritanian = 'Mauritanian';
    case Mauritian = 'Mauritian';
    case Mexican = 'Mexican';
    case Micronesian = 'Micronesian';
    case Moldovan = 'Moldovan';
    case Monacan = 'Monacan';
    case Mongolian = 'Mongolian';
    case Moroccan = 'Moroccan';
    case Mosotho = 'Mosotho';
    case Motswana = 'Motswana';
    case Mozambican = 'Mozambican';
    case Namibian = 'Namibian';
    case Nauruan = 'Nauruan';
    case Nepalese = 'Nepalese';
    case NewZealander = 'New Zealander';
    case Nicaraguan = 'Nicaraguan';
    case Nigerian = 'Nigerian';
    case Nigerien = 'Nigerien';
    case NorthKorean = 'North Korean';
    case Norwegian = 'Norwegian';
    case Omani = 'Omani';
    case Pakistani = 'Pakistani';
    case Palauan = 'Palauan';
    case Panamanian = 'Panamanian';
    case PapuaNewGuinean = 'Papua New Guinean';
    case Paraguayan = 'Paraguayan';
    case Peruvian = 'Peruvian';
    case Polish = 'Polish';
    case Portuguese = 'Portuguese';
    case Qatari = 'Qatari';
    case Romanian = 'Romanian';
    case Russian = 'Russian';
    case Rwandan = 'Rwandan';
    case SaintLucian = 'Saint Lucian';
    case Salvadoran = 'Salvadoran';
    case Samoan = 'Samoan';
    case SanMarinese = 'San Marinese';
    case SaoTomean = 'Sao Tomean';
    case Saudi = 'Saudi';
    case Scottish = 'Scottish';
    case Senegalese = 'Senegalese';
    case Serbian = 'Serbian';
    case Seychellois = 'Seychellois';
    case SierraLeonean = 'Sierra Leonean';
    case Singaporean = 'Singaporean';
    case Slovakian = 'Slovakian';
    case Slovenian = 'Slovenian';
    case SolomonIslander = 'Solomon Islander';
    case Somali = 'Somali';
    case SouthAfrican = 'South African';
    case SouthKorean = 'South Korean';
    case Spanish = 'Spanish';
    case SriLankan = 'Sri Lankan';
    case Sudanese = 'Sudanese';
    case Surinamer = 'Surinamer';
    case Swazi = 'Swazi';
    case Swedish = 'Swedish';
    case Swiss = 'Swiss';
    case Syrian = 'Syrian';
    case Taiwanese = 'Taiwanese';
    case Tajik = 'Tajik';
    case Tanzanian = 'Tanzanian';
    case Thai = 'Thai';
    case Togolese = 'Togolese';
    case Tongan = 'Tongan';
    case TrinidadianOrTobagonian = 'Trinidadian or Tobagonian';
    case Tunisian = 'Tunisian';
    case Turkish = 'Turkish';
    case Tuvaluan = 'Tuvaluan';
    case Ugandan = 'Ugandan';
    case Ukrainian = 'Ukrainian';
    case Uruguayan = 'Uruguayan';
    case Uzbekistani = 'Uzbekistani';
    case Venezuelan = 'Venezuelan';
    case Vietnamese = 'Vietnamese';
    case Welsh = 'Welsh';
    case Yemenite = 'Yemenite';
    case Zambian = 'Zambian';
    case Zimbabwean = 'Zimbabwean';

    public function label(): string
    {
        return $this->value;
    }

    /**
     * @return array<string, string>
     */
    public static function options(): array
    {
        return collect(self::cases())
            ->mapWithKeys(fn (self $case) => [$case->value => $case->label()])
            ->toArray();
    }
}
